### ISSUE TITLE
WatchOS Minimum Deployment Target

### ISSUE THREAD

**Issue by nickruddeni** [newrelic/newrelic-ios-agent#305]
Hi, we're integrating the new WatchOS agent (thanks for adding that). The minimum deployment target for the agent is currently set to 10. Our app currently has WatchOS 9 as a minimum deployment target and ideally we'd like to keep it that way as we typically stick with the N - 2 approach for supported versions and we still have a number of watch app users using 9.

Question is: Can we definitely not reliably use the WatchOS agent on iOS 9? Or are there specific features or APIs we can avoid to use it safely? We are essentially only using the agent for logging custom events on the watch.

Thanks

**Comment by mbruin-NR** [comment]
Thank you for your question from it I discovered that our project minimumDeployment is different from the cocoa pods and spm.  Also to answer your question I checked our api usage and didn't find an area that would cause an issue for watchOS 9.
