### ISSUE TITLE
Facing memory leak NewRelic.start(_: _) method around 2 kb.

### ISSUE THREAD

**Issue by shravanteegala** [newrelic/newrelic-ios-agent#322]
When i run my iOS application i find the memory leak at NewRelic.start(withApplicationToken: newRelicToken) method.
 method specification: +(void)startWithApplicationToken:(NSString* _Nonnull)appToken;

**Comment by mbruin-NR** [comment]
We are not seeing this leak with the Xcode Leaks instrument. Could you tell us more about what you are seeing?
[TestAppNoLeaks.trace.zip](https://github.com/user-attachments/files/17668358/TestAppNoLeaks.trace.zip)
