### ISSUE TITLE
NewRelicAgent 7.5.2 fails downloading

### ISSUE THREAD

**Issue by cristik** [newrelic/newrelic-ios-agent#327]
The latest NewRelicAgent version - 7.5.2 - cannot be installed by CocoaPods. The server where the xcframework is hosted responds with `Error 503 Response object too large`.

## Description
As stated above, NewRelicAgent 7.5.2 cannot be used in an iOS project that uses Cocoapods due to the XCFrameworks file download failing.

## Steps to Reproduce
1. Start a new project and configure it with Cocoapods, or use an existing one
2. Add the `pod 'NewRelicAgent', '7.5.2'` to a target
3. Run `pod install`

## Expected Behavior
The pods successfully install.

## Relevant Logs / Console output
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing NewRelicAgent (7.5.2)

[!] Error installing NewRelicAgent
[!] /usr/bin/curl -f -L -o /var/folders/cg/ld1r2k3d4kj97tsz6_1hbc5w0000gn/T/d20241109-41722-1x2fvlo/file.zip https://download.newrelic.com/ios_agent/NewRelic_XCFramework_Agent_7.5.2.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.16.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   472    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 503

```

`curl -v https://download.newrelic.com/ios_agent/NewRelic_XCFramework_Agent_7.5.2.zip` gives a similar response, though with more details.

Opening the URL in a web browser results in the same error:
<img width="514" alt="Screenshot 2024-11-09 at 07 41 49" src="https://github.com/user-attachments/assets/43fc8340-6d35-4c62-9f5a-6c9f7e539f45">

## Your Environment
MacOS Sequoia 15.0.1 (24A348)
Xcode 16.1 (16B40)
Cocoapods 1.16.2
 
## Additional context
None

**Comment by JustinRush-NR** [comment]
This was related to an outage in New Relic's download site at https://download.newrelic.com/ over the weekend.

I have verified that asset is now available again.
